/**
 * CODE IN THIS FILE IS AUTO-GENERATED!
 * DO NOT MAKE MANUAL CHANGES BECAUSE THEY WILL BE LOST
*/

import { Ability, AbilityMetaCategory } from './enums';
import { type AbilityInfo } from './types';

export const ABILITIES: AbilityInfo[] = [
  {
    ability: Ability.CreateEgg,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "That poor chick never had a chance...",
    name: "Brood Parasite",
    description: "When [creature] is played, an Egg is created on the opposing space.",
    rawName: "CreateEgg",
  },
  {
    ability: Ability.DoubleStrike,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 4,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Double Strike",
    description: "[creature] will strike the opposing space an extra time when attacking.",
    rawName: "DoubleStrike",
  },
  {
    ability: Ability.GainAttackOnKill,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "A gruesome way to grow...",
    name: "Blood Lust",
    description: "When [creature] attacks an opposing creature and it perishes, this card gains 1 power.",
    rawName: "GainAttackOnKill",
  },
  {
    ability: Ability.HydraEgg,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Behold...",
    name: "Finical Hatchling",
    description: "[creature] hatches when drawn if the numbers 1 to 5 are represented in the health of creatures in your deck, and in their power, and if there is a creature of each tribe in your deck.",
    rawName: "HydraEgg",
  },
  {
    ability: Ability.MadeOfStone,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part1Rulebook],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Made Of Stone",
    description: "[creature] is immune to the effects of Touch of Death and Stinky.",
    rawName: "MadeOfStone",
  },
  {
    ability: Ability.Morsel,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Morsel",
    description: "When [creature] is sacrificed, it adds its stat values to the card it was sacrificed for.",
    rawName: "Morsel",
  },
  {
    ability: Ability.OpponentBones,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "[c:bR]Get your paws off of my creature's bones![c:]",
    name: "Scavenger",
    description: "While [creature] is on the board, opposing creatures also provide bones when perishing.",
    rawName: "OpponentBones",
  },
  {
    ability: Ability.StrafeSwap,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "I do not envy those that stand in the Bull's way...",
    name: "Rampager",
    description: "At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. Creatures in the way will be thrown back behind it.",
    rawName: "StrafeSwap",
  },
  {
    ability: Ability.ActivatedDealDamage,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Energy Gun",
    description: "Pay 1 Energy to deal 1 damage to the creature across from [creature].",
    rawName: "ActivatedDealDamage",
  },
  {
    ability: Ability.ActivatedDrawSkeleton,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Disentomb",
    description: "Pay 1 Bone to create a Skeleton in your hand.",
    rawName: "ActivatedDrawSkeleton",
  },
  {
    ability: Ability.ActivatedEnergyToBones,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Bonehorn",
    description: "Pay 1 Energy to gain 3 Bones.",
    rawName: "ActivatedEnergyToBones",
  },
  {
    ability: Ability.ActivatedHeal,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 1,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Marrow Sucker",
    description: "Pay 2 Bones to heal [creature].",
    rawName: "ActivatedHeal",
  },
  {
    ability: Ability.ActivatedRandomPowerBone,
    passive: true,
    activated: false,
    metaCategories: [],
    powerLevel: 5,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "",
    description: "",
    rawName: "ActivatedRandomPowerBone",
  },
  {
    ability: Ability.ActivatedRandomPowerEnergy,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 5,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Power Dice",
    description: "Pay 1 Energy to set the power of [creature] randomly between 1 and 6.",
    rawName: "ActivatedRandomPowerEnergy",
  },
  {
    ability: Ability.ActivatedSacrificeDrawCards,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "True Scholar",
    description: "If you have a Blue gem, sacrifice [creature] to draw 3 cards.",
    rawName: "ActivatedSacrificeDrawCards",
  },
  {
    ability: Ability.ActivatedStatsUp,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Enlarge",
    description: "Pay 2 Bones to increase the power and health of [creature] by 1.",
    rawName: "ActivatedStatsUp",
  },
  {
    ability: Ability.ActivatedStatsUpEnergy,
    passive: false,
    activated: true,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Stimulate",
    description: "Pay 3 Energy to increase the power and health of [creature] by 1.",
    rawName: "ActivatedStatsUpEnergy",
  },
  {
    ability: Ability.BombSpawner,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Bomb Spewer",
    description: "When [creature] is played, fill all empty spaces with Explode Bots.",
    rawName: "BombSpawner",
  },
  {
    ability: Ability.BoneDigger,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.GrimoraRulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 2,
    opponentUsable: false,
    canStack: true,
    abilityLearnedDialogue: "",
    name: "Bone Digger",
    description: "At the end of the owner's turn, [creature] will generate 1 Bone.",
    rawName: "BoneDigger",
  },
  {
    ability: Ability.Brittle,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.GrimoraRulebook, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.Part1Rulebook],
    powerLevel: -2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Brittle",
    description: "After attacking, [creature] perishes.",
    rawName: "Brittle",
  },
  {
    ability: Ability.BuffGems,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gem Animator",
    description: "Mox cards on the owner's side of the board gain 1 power.",
    rawName: "BuffGems",
  },
  {
    ability: Ability.ConduitBuffAttack,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Attack Conduit",
    description: "Other creatures within a circuit completed by [creature] gain 1 power.",
    rawName: "ConduitBuffAttack",
  },
  {
    ability: Ability.ConduitEnergy,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Energy Conduit",
    description: "If [creature] is part of a completed circuit, your Energy never depletes.",
    rawName: "ConduitEnergy",
  },
  {
    ability: Ability.ConduitFactory,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Spawn Conduit",
    description: "Empty spaces within a circuit completed by [creature] spawn L33pB0ts at the end of the owner's turn.",
    rawName: "ConduitFactory",
  },
  {
    ability: Ability.ConduitHeal,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Healing Conduit",
    description: "Other creatures within a circuit completed by [creature] are healed at the end of the owner's turn.",
    rawName: "ConduitHeal",
  },
  {
    ability: Ability.ConduitNull,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Null Conduit",
    description: "[creature] may complete a circuit, but provides no effect.",
    rawName: "ConduitNull",
  },
  {
    ability: Ability.DoubleDeath,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Handy",
    description: "When another creature you own dies, it is returned to life and dies again immediately.",
    rawName: "DoubleDeath",
  },
  {
    ability: Ability.DrawNewHand,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Handy",
    description: "When [creature] is played, discard your hand then draw a new hand of 4 cards.",
    rawName: "DrawNewHand",
  },
  {
    ability: Ability.DropRubyOnDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Ruby Heart",
    description: "When [creature] perishes, a Ruby Mox is created in its place.",
    rawName: "DropRubyOnDeath",
  },
  {
    ability: Ability.ExplodeOnDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 0,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Detonator",
    description: "When [creature] dies, the creature opposing it, as well as adjacent friendly creatures, are dealt 10 damage.",
    rawName: "ExplodeOnDeath",
  },
  {
    ability: Ability.GainBattery,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Battery Bearer",
    description: "When [creature] is played, it provides an Energy Cell to its owner.",
    rawName: "GainBattery",
  },
  {
    ability: Ability.GainGemBlue,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Blue Mox",
    description: "While [creature] is on the board, it provides a Blue Gem to its owner.",
    rawName: "GainGemBlue",
  },
  {
    ability: Ability.GainGemGreen,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Green Mox",
    description: "While [creature] is on the board, it provides a Green Gem to its owner.",
    rawName: "GainGemGreen",
  },
  {
    ability: Ability.GainGemOrange,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Orange Mox",
    description: "While [creature] is on the board, it provides an Orange Gem to its owner.",
    rawName: "GainGemOrange",
  },
  {
    ability: Ability.GainGemTriple,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Great Mox",
    description: "While [creature] is on the board, it provides a Green, Orange, and Blue gem to its owner.",
    rawName: "GainGemTriple",
  },
  {
    ability: Ability.GemDependant,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: -3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gem Dependant",
    description: "If [creature]'s owner controls no Mox cards, [creature] perishes.",
    rawName: "GemDependant",
  },
  {
    ability: Ability.GemsDraw,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 3,
    opponentUsable: false,
    canStack: true,
    abilityLearnedDialogue: "",
    name: "Mental Gemnastics",
    description: "When [creature] is played, you draw cards equal to the amount of Mox cards on your side of the board.",
    rawName: "GemsDraw",
  },
  {
    ability: Ability.Loot,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Looter",
    description: "When [creature] deals damage directly, draw a card for each damage dealt.",
    rawName: "Loot",
  },
  {
    ability: Ability.PreventAttack,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 4,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Repulsive",
    description: "If a creature would attack [creature], it does not.",
    rawName: "PreventAttack",
  },
  {
    ability: Ability.SkeletonStrafe,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Skeleton Crew",
    description: "At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil and drop a Skeleton in its old space.",
    rawName: "SkeletonStrafe",
  },
  {
    ability: Ability.SquirrelStrafe,
    passive: false,
    activated: false,
    metaCategories: [],
    powerLevel: 4,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Squirrel Shedder",
    description: "At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil and drop a Squirrel in their old space.",
    rawName: "SquirrelStrafe",
  },
  {
    ability: Ability.SubmergeSquid,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Waterborne",
    description: "[creature] submerges itself during its opponent's turn. While submerged, opposing creatures attack its owner directly.",
    rawName: "SubmergeSquid",
  },
  {
    ability: Ability.BloodGuzzler,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Blood Guzzler",
    description: "When a creature bearing this sigil deals damage, it gains 1 health for each damage dealt.",
    rawName: "BloodGuzzler",
  },
  {
    ability: Ability.Apparition,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Apparition",
    description: "A creature bearing this sigil gains 1 power when you speak 'Bloody Mary' into a connected microphone up to a total of 13 times.",
    rawName: "BloodyMary",
  },
  {
    ability: Ability.ExplodingCorpse,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Exploding Corpse",
    description: "When a creature bearing this sigil dies, all empty spaces on the board are filled with a Guts card.",
    rawName: "ExplodingCorpse",
  },
  {
    ability: Ability.Haunter,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Haunter",
    description: "When a creature bearing this sigil dies, it haunts the space it died in. Creatures played on this space gain its old sigils.",
    rawName: "Haunter",
  },
  {
    ability: Ability.EdaxioArms,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Arms of Edaxio",
    description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio.",
    rawName: "EdaxioArms",
  },
  {
    ability: Ability.EdaxioHead,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Head of Edaxio",
    description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio.",
    rawName: "EdaxioHead",
  },
  {
    ability: Ability.EdaxioLegs,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Legs of Edaxio",
    description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio.",
    rawName: "EdaxioLegs",
  },
  {
    ability: Ability.EdaxioTorso,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Torso of Edaxio",
    description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio.",
    rawName: "EdaxioTorso",
  },
  {
    ability: Ability.VirtualReality,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Virtual Realist",
    description: "If a VR headset is connected, a creature bearing this sigil may be played without paying its cost.",
    rawName: "VirtualReality",
  },
  {
    ability: Ability.AllStrike,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook],
    powerLevel: 5,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Omni Strike",
    description: "[creature] will strike each opposing space that is occupied by a creature. It will strike directly if no creatures oppose it.",
    rawName: "AllStrike",
  },
  {
    ability: Ability.BeesOnHit,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Bees Within",
    description: "Once [creature] is struck, a Bee is created in your hand. [define:Bee]",
    rawName: "BeesOnHit",
  },
  {
    ability: Ability.BuffNeighbours,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Leader",
    description: "Creatures adjacent to [creature] gain 1 power.",
    rawName: "BuffNeighbours",
  },
  {
    ability: Ability.CorpseEater,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Corpses are in no short supply.",
    name: "Corpse Eater",
    description: "If a creature that you own perishes by combat, [creature] in your hand is automatically played in its place.",
    rawName: "CorpseEater",
  },
  {
    ability: Ability.CreateBells,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Bellist",
    description: "When [creature] is played, a Chime is created on each empty adjacent space. [define:DausBell]",
    rawName: "CreateBells",
  },
  {
    ability: Ability.CreateDams,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "A formidable defense.",
    name: "Dam Builder",
    description: "When [creature] is played, a Dam is created on each empty adjacent space. [define:Dam]",
    rawName: "CreateDams",
  },
  {
    ability: Ability.Deathtouch,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 4,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "A serpent perhaps more deadly than Man.",
    name: "Touch of Death",
    description: "When [creature] damages another creature, that creature perishes.",
    rawName: "Deathtouch",
  },
  {
    ability: Ability.DebuffEnemy,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Stinky",
    description: "The creature opposing [creature] loses 1 power.",
    rawName: "DebuffEnemy",
  },
  {
    ability: Ability.DrawAnt,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Power in numbers - The Ant's creed.",
    name: "Ant Spawner",
    description: "When [creature] is played, an Ant is created in your hand.",
    rawName: "DrawAnt",
  },
  {
    ability: Ability.DrawCopy,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 3,
    opponentUsable: false,
    canStack: true,
    abilityLearnedDialogue: "Licentious Field Mice... always breeding.",
    name: "Fecundity",
    description: "When [creature] is played, a copy of it is created in your hand.",
    rawName: "DrawCopy",
  },
  {
    ability: Ability.DrawCopyOnDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Were you as unfaltering as the Cockroach...",
    name: "Unkillable",
    description: "When [creature] perishes, a copy of it is created in your hand.",
    rawName: "DrawCopyOnDeath",
  },
  {
    ability: Ability.DrawRabbits,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Never doubt the fecundity of rabbits.",
    name: "Rabbit Hole",
    description: "When [creature] is played, a Rabbit is created in your hand. [define:Rabbit]",
    rawName: "DrawRabbits",
  },
  {
    ability: Ability.Evolve,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "They grow up so fast.",
    name: "Fledgling",
    description: "[creature] will grow into a more powerful form after 1 turn on the board.",
    rawName: "Evolve",
  },
  {
    ability: Ability.Flying,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 0,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Airborne",
    description: "[creature] will strike an opponent directly, even if there is a creature opposing it.",
    rawName: "Flying",
  },
  {
    ability: Ability.GuardDog,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "Who let that dog out?",
    name: "Guardian",
    description: "When an opposing creature is placed opposite to an empty space, [creature] will move to that empty space.",
    rawName: "GuardDog",
  },
  {
    ability: Ability.IceCube,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Frozen Away",
    description: "When [creature] perishes, the creature inside is released in its place.",
    rawName: "IceCube",
  },
  {
    ability: Ability.QuadrupleBones,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "So many bones...",
    name: "Bone King",
    description: "When [creature] dies, 4 bones are awarded instead of 1.",
    rawName: "QuadrupleBones",
  },
  {
    ability: Ability.RandomAbility,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Amorphous",
    description: "When [creature] is drawn, this sigil is replaced with another sigil at random.",
    rawName: "RandomAbility",
  },
  {
    ability: Ability.RandomConsumable,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 5,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Trinket Bearer",
    description: "When [creature] is played, you will receive a random item as long as your pack is not full.",
    rawName: "RandomConsumable",
  },
  {
    ability: Ability.Reach,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Mighty Leap",
    description: "[creature] will block an opposing creature bearing the Airborne sigil.",
    rawName: "Reach",
  },
  {
    ability: Ability.Sacrificial,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Many Lives",
    description: "When [creature] is sacrificed it does not perish.",
    rawName: "Sacrificial",
  },
  {
    ability: Ability.Sharp,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "A thorny rebuke.",
    name: "Sharp Quills",
    description: "Once [creature] is struck, the striker is then dealt a single damage point.",
    rawName: "Sharp",
  },
  {
    ability: Ability.Sinkhole,
    passive: true,
    activated: false,
    metaCategories: [],
    powerLevel: 5,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "",
    description: "",
    rawName: "Sinkhole",
  },
  {
    ability: Ability.SplitStrike,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 4,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Bifurcated Strike",
    description: "[creature] will strike each opposing space to the left and right of the space across from it.",
    rawName: "SplitStrike",
  },
  {
    ability: Ability.SquirrelOrbit,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook],
    powerLevel: 5,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Tidal Lock",
    description: "At the beginning of its owner's turn, [creature] will pull small creatures, like Squirrels, into its orbit.",
    rawName: "SquirrelOrbit",
  },
  {
    ability: Ability.SteelTrap,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook],
    powerLevel: 5,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Steel Trap",
    description: "When [creature] perishes, the creature opposing it perishes as well. A pelt is created in your hand.",
    rawName: "SteelTrap",
  },
  {
    ability: Ability.Strafe,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "Fleeing will not save you.",
    name: "Sprinter",
    description: "At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil.",
    rawName: "Strafe",
  },
  {
    ability: Ability.StrafePush,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "The might of the Moose cannot be halted.",
    name: "Hefty",
    description: "At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. Creatures in the way will be pushed in the same direction.",
    rawName: "StrafePush",
  },
  {
    ability: Ability.Submerge,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "Hold your breath...",
    name: "Waterborne",
    description: "[creature] submerges itself during its opponent's turn. While submerged, opposing creatures attack its owner directly.",
    rawName: "Submerge",
  },
  {
    ability: Ability.TailOnHit,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "It's hard to call it cowardly...",
    name: "Loose Tail",
    description: "When [creature] would be struck, a Tail is created in its place and [creature] moves to the right.",
    rawName: "TailOnHit",
  },
  {
    ability: Ability.TripleBlood,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular],
    powerLevel: 2,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Worthy Sacrifice",
    description: "[creature] is counted as 3 Blood rather than 1 Blood when sacrificed.",
    rawName: "TripleBlood",
  },
  {
    ability: Ability.TriStrike,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part3Rulebook],
    powerLevel: 5,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Trifurcated Strike",
    description: "[creature] will strike each opposing space to the left, right, and center of it.",
    rawName: "TriStrike",
  },
  {
    ability: Ability.Tutor,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 4,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Shiny.",
    name: "Hoarder",
    description: "When [creature] is played, you may search your deck for any card and take it into your hand.",
    rawName: "Tutor",
  },
  {
    ability: Ability.WhackAMole,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part1Rulebook, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "Meddlesome Mole...",
    name: "Burrower",
    description: "When an empty space would be struck, [creature] will move to that space to receive the strike instead.",
    rawName: "WhackAMole",
  },
  {
    ability: Ability.BuffEnemy,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.Part1Rulebook],
    powerLevel: -1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Annoying",
    description: "The creature opposing [creature] gains 1 power.",
    rawName: "BuffEnemy",
  },
  {
    ability: Ability.CellBuffSelf,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Buff When Powered",
    description: "If [creature] is within a circuit, it gains 2 power.",
    rawName: "CellBuffSelf",
  },
  {
    ability: Ability.CellDrawRandomCardOnDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gift When Powered",
    description: "If [creature] is within a circuit when it perishes, a random card is created in your hand.",
    rawName: "CellDrawRandomCardOnDeath",
  },
  {
    ability: Ability.CellTriStrike,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Trifurcated When Powered",
    description: "If [creature] is within a circuit, it will strike each opposing space to the left, right, and center of it.",
    rawName: "CellTriStrike",
  },
  {
    ability: Ability.ConduitSpawnGems,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gem Spawn Conduit",
    description: "Empty spaces within a circuit completed by [creature] spawn Gem Vessels at the end of the owner's turn.",
    rawName: "ConduitSpawnGems",
  },
  {
    ability: Ability.DeathShield,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard, AbilityMetaCategory.Part1Modular, AbilityMetaCategory.AscensionUnlocked],
    powerLevel: 4,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Armored",
    description: "The first time [creature] would take damage, prevent that damage.",
    rawName: "DeathShield",
  },
  {
    ability: Ability.DeleteFile,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 0,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Hostage File",
    description: "When [creature] perishes the file used to create it is really deleted from your Hard Drive.",
    rawName: "DeleteFile",
  },
  {
    ability: Ability.DrawRandomCardOnDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gift Bearer",
    description: "When [creature] perishes, a random card is created in your hand.",
    rawName: "DrawRandomCardOnDeath",
  },
  {
    ability: Ability.DrawVesselOnHit,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Vessel Printer",
    description: "Once [creature] is struck, draw a card from your Empty Vessel pile.",
    rawName: "DrawVesselOnHit",
  },
  {
    ability: Ability.ExplodeGems,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gem Detonator",
    description: "When Gem Vessels on the owner's side of the board die, they Detonate (the creature opposing them, as well as adjacent friendly creatures, are dealt 10 damage).",
    rawName: "ExplodeGems",
  },
  {
    ability: Ability.FileSizeDamage,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 5,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Dead Byte",
    description: "When [creature] perishes, select a file. Place damage on the scales according to the file's size.",
    rawName: "FileSizeDamage",
  },
  {
    ability: Ability.LatchBrittle,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 3,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Brittle Latch",
    description: "When [creature] perishes, its owner chooses a creature to gain the Brittle sigil.",
    rawName: "LatchBrittle",
  },
  {
    ability: Ability.LatchDeathShield,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Shield Latch",
    description: "When [creature] perishes, its owner chooses a creature to gain the Nano Armor sigil.",
    rawName: "LatchDeathShield",
  },
  {
    ability: Ability.LatchExplodeOnDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.GrimoraRulebook],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Bomb Latch",
    description: "When [creature] perishes, its owner chooses a creature to gain the Detonator sigil.",
    rawName: "LatchExplodeOnDeath",
  },
  {
    ability: Ability.MoveBeside,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.GrimoraRulebook, AbilityMetaCategory.MagnificusRulebook],
    powerLevel: 0,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Clinger",
    description: "When one of your creatures is placed in a space, [creature] will move towards them as far as possible.",
    rawName: "MoveBeside",
  },
  {
    ability: Ability.PermaDeath,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular],
    powerLevel: -1,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "Well, you won't be seeing that one again...",
    name: "Overclocked",
    description: "[creature] has increased power. But, if [creature] perishes, it is permanently removed from your deck.",
    rawName: "PermaDeath",
  },
  {
    ability: Ability.Sentry,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 3,
    opponentUsable: true,
    canStack: true,
    abilityLearnedDialogue: "",
    name: "Sentry",
    description: "When a creature moves into the space opposing [creature], they are dealt 1 damage.",
    rawName: "Sentry",
  },
  {
    ability: Ability.ShieldGems,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular],
    powerLevel: 2,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Gem Guardian",
    description: "When [creature] is played, all Gem Vessels on the owners' side of the board gain Nano Armor.",
    rawName: "ShieldGems",
  },
  {
    ability: Ability.Sniper,
    passive: true,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.Part3BuildACard],
    powerLevel: 3,
    opponentUsable: false,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Sniper",
    description: "You may choose which opposing space [creature] strikes.",
    rawName: "Sniper",
  },
  {
    ability: Ability.SwapStats,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook, AbilityMetaCategory.Part3Modular, AbilityMetaCategory.BountyHunter],
    powerLevel: 0,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Swapper",
    description: "After [creature] is dealt damage, swap its Power and Health.",
    rawName: "SwapStats",
  },
  {
    ability: Ability.Transformer,
    passive: false,
    activated: false,
    metaCategories: [AbilityMetaCategory.Part3Rulebook],
    powerLevel: 1,
    opponentUsable: true,
    canStack: false,
    abilityLearnedDialogue: "",
    name: "Transformer",
    description: "At the beginning of your turn [creature] will transform to, or from, Beast mode.",
    rawName: "Transformer",
  },
];
